/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Person.Person;
import Business.Profiles.FacultyProfile;
import Business.UserAccounts.UserAccount;
import javax.swing.table.DefaultTableModel;
import Business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JTable;
import university.CourseCatalog.Course;
import university.CourseCatalog.CourseCatalog;
import university.CourseSchedule.CourseOffer;
import university.CourseSchedule.CourseSchedule;
import university.CourseSchedule.Seats;
import university.Department.Department;

/**
 *
 * @author mmoly
 */
public class ManageStudentProfileJPanel extends javax.swing.JPanel {

       JPanel CardSequencePanel;
        Business business;
        final UserAccount user;
    /**
     * Creates new form ManageCourse
     */
    public ManageStudentProfileJPanel(Business bz, UserAccount u, JPanel jp) {
        this.user = u;
        CardSequencePanel = jp;
        this.business = bz;
        if (Business.Authorize(u,"Faculty")) initComponents();
    }

   public void populateStudentProfiles(CourseSchedule schedule, FacultyProfile faculty, JTable targetTable) {
        // Your explicit table layout definition
        String[] columnHeaders = {"Course Name", "CRN", "Credits", "NUID", "Enrolled", "Open Seats"};
        
        DefaultTableModel model = new DefaultTableModel(columnHeaders, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make the visual grid cells locked/read-only
            }
        };

        // Safety verification check
        if (schedule == null || faculty == null || targetTable == null) {
            return;
        }

        // Access the schedule array list (Ensure getSchedule() exists in CourseSchedule)
        for (CourseOffer offer : schedule.getSchedule()) {
            
            // Confirm a teacher is assigned and matches the logged-in profile instance
            if (offer.getFacultyProfile() != null && offer.getFacultyProfile().equals(faculty)) {
                
                Course baseCourse = offer.getSubjectCourse();
                
                // Track counters by looping through the internal seat list
                int enrolledCount = 0;
                int openSeatsCount = 0;
                
                // Note: Ensure getSeatList() or a similar accessor exists in CourseOffer.java to read seats.
                // If it doesn't exist, see the getter addition below.
                for (Seats seat : offer.getSeatlist()) {
                    if (seat.isOccupied()) {
                        enrolledCount++;
                    } else {
                        openSeatsCount++;
                    }
                }

                // Construct row data matching your exact column setup
                Object[] rowData = new Object[6];
                rowData[0] = baseCourse.getName();              // "Course Name"
                rowData[1] = offer.getCourseNumber();          // "CRN" (Mapping Course number to CRN)
                rowData[2] = offer.getCreditHours();           // "Credits"
                rowData[3] = faculty.getPerson().getPersonId(); // "NUID" (Logged-in Faculty Person ID)
                rowData[4] = enrolledCount;                    // "Enrolled"
                rowData[5] = openSeatsCount;                   // "Open Seats"

                model.addRow(rowData);
            }
        }

        // Push your customized matrix blueprint onto your UI table object
        ManageStudentTable.setModel(model);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ManageStudentTable = new javax.swing.JTable();
        btnNext = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        ManageStudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ManageStudentTable);

        btnNext.setText("Next");

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addGap(275, 275, 275))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(Back))
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
    CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTable ManageStudentTable;
    private javax.swing.JButton btnNext;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
