/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;
import Business.Business;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nicholaswoodward
 */
public class StudentRegistrationJPanel extends javax.swing.JPanel {
Business business;
StudentProfile student;
JPanel CardSequencePanel;
    /**
     * Creates new form StudentRegistrationJPanel
     */
public StudentRegistrationJPanel(Business b, StudentProfile sp, JPanel csp) {
    business = b;
    student = sp;
    CardSequencePanel = csp;

    initComponents();

    populateCourseTable();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        lblTitle.setText("Course Registration");

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCourses);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDrop.setText("Drop Course");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDrop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegister)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnDrop)
                    .addComponent(btnRegister))
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
    registerCourse();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
    dropCourse();
    }//GEN-LAST:event_btnDropActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnRegister;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCourses;
    // End of variables declaration//GEN-END:variables
    private void populateCourseTable() {
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();

        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"Course", "CRN", "Credits", "Status"});

        model.addRow(new Object[]{"INFO5100", "5100", "4", "Available"});
        model.addRow(new Object[]{"INFO6205", "6205", "4", "Available"});
        model.addRow(new Object[]{"INFO6105", "6105", "4", "Available"});
        model.addRow(new Object[]{"DAMG6210", "6210", "4", "Available"});
    }
private void registerCourse() {
    int selectedRow = tblCourses.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a course first.");
        return;
    }

    String status = tblCourses.getValueAt(selectedRow, 3).toString();

    if (status.equals("Registered")) {
        JOptionPane.showMessageDialog(this, "You are already registered for this course.");
        return;
    }

    tblCourses.setValueAt("Registered", selectedRow, 3);
    JOptionPane.showMessageDialog(this, "Course registered successfully.");
}

private void dropCourse() {
    int selectedRow = tblCourses.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a course first.");
        return;
    }

    String status = tblCourses.getValueAt(selectedRow, 3).toString();

    if (!status.equals("Registered")) {
        JOptionPane.showMessageDialog(this, "You are not registered for this course.");
        return;
    }

    tblCourses.setValueAt("Available", selectedRow, 3);
    JOptionPane.showMessageDialog(this, "Course dropped successfully.");
}

private void goBack() {
    CardSequencePanel.remove(this);
    ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}}
