/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;
import Business.Business;
import Business.Profiles.StudentAccount;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nicholaswoodward
 */
public class StudentCourseworkJPanel extends javax.swing.JPanel {

    Business business;
    StudentProfile student;
    JPanel CardSequencePanel;
    final StudentAccount studentAccount;

    /**
     * Creates new form StudentCourseworkJPanel
     */
    public StudentCourseworkJPanel(Business b, StudentAccount sa, StudentProfile sp, JPanel csp) {
        this.studentAccount = sa;
        business = b;
        student = sp;
        CardSequencePanel = csp;
        if (Business.Authorize(sa, "Student")) initComponents();
        populateCourseworkTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblTitle = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCoursework = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnViewProgress = new javax.swing.JButton();
        btnSubmitAssignment = new javax.swing.JButton();

        tblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        tblTitle.setText("Course Work");

        tblCoursework.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCoursework);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewProgress.setText("View Progress");
        btnViewProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProgressActionPerformed(evt);
            }
        });

        btnSubmitAssignment.setText("Submit Assignment");
        btnSubmitAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAssignmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewProgress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmitAssignment))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnViewProgress)
                    .addComponent(btnSubmitAssignment))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProgressActionPerformed
    viewSelectedProgress();
    }//GEN-LAST:event_btnViewProgressActionPerformed

    private void btnSubmitAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAssignmentActionPerformed
    submitSelectedAssignment();
    }//GEN-LAST:event_btnSubmitAssignmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitAssignment;
    private javax.swing.JButton btnViewProgress;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCoursework;
    private java.awt.Label tblTitle;
    // End of variables declaration//GEN-END:variables

    private void populateCourseworkTable() {
    DefaultTableModel model = (DefaultTableModel) tblCoursework.getModel();

    model.setRowCount(0);
    model.setColumnIdentifiers(new Object[]{"Course", "Assignment", "Status", "Progress"});

    addAssignmentRow(model, "INFO5100", "Student Profile Feature");
    addAssignmentRow(model, "INFO5100", "Coursework Panel");
    addAssignmentRow(model, "INFO5100", "Registration Feature");
    addAssignmentRow(model, "INFO5100", "Graduation Audit");
}

private void addAssignmentRow(DefaultTableModel model, String courseCode, String assignmentName) {
    String status = student.isAssignmentSubmitted(assignmentName) ? "Submitted" : "Not Submitted";
    String progress = student.isAssignmentSubmitted(assignmentName) ? "100%" : "0%";

    model.addRow(new Object[]{courseCode, assignmentName, status, progress});
}

    private void submitSelectedAssignment() {
        int selectedRow = tblCoursework.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an assignment first.");
            return;
        }
String assignmentName = tblCoursework.getValueAt(selectedRow, 1).toString();
student.submitAssignment(assignmentName);
        tblCoursework.setValueAt("Submitted", selectedRow, 2);
        tblCoursework.setValueAt("100%", selectedRow, 3);

        JOptionPane.showMessageDialog(this, "Assignment submitted successfully.");
    }

    private void viewSelectedProgress() {
        int selectedRow = tblCoursework.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an assignment first.");
            return;
        }

        String course = tblCoursework.getValueAt(selectedRow, 0).toString();
        String assignment = tblCoursework.getValueAt(selectedRow, 1).toString();
        String status = tblCoursework.getValueAt(selectedRow, 2).toString();
        String progress = tblCoursework.getValueAt(selectedRow, 3).toString();

        JOptionPane.showMessageDialog(this,
                "Course: " + course
                + "\nAssignment: " + assignment
                + "\nStatus: " + status
                + "\nProgress: " + progress,
                "Coursework Progress",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void goBack() {
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }
}
