/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Profiles.StudentAccount;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Student panel for registering for and dropping available courses.
 *
 * @author Nicholas Woodward
 */
public class StudentRegistrationJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    private Business business;
    private StudentProfile student;
    private JPanel CardSequencePanel;
    private final StudentAccount studentAccount;

    // CONSTRUCTOR
    /**
     * Creates a new StudentRegistrationJPanel for an authenticated student.
     *
     * @param b business object
     * @param sa authenticated student account
     * @param sp student profile
     * @param csp parent CardLayout panel
     */
    public StudentRegistrationJPanel(Business b, StudentAccount sa, StudentProfile sp, JPanel csp) {
        business = b;
        student = sp;
        CardSequencePanel = csp;
        studentAccount = sa;

        if (Business.Authorize(sa, "Student")) {
            initComponents();
            setBackground(new java.awt.Color(240, 248, 255));
            populateCourseTable();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        lblTitle.setText("Course Registration");

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCourses);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDrop.setText("Drop Course");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDrop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegister)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnDrop)
                    .addComponent(btnRegister))
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
    registerCourse();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
    dropCourse();
    }//GEN-LAST:event_btnDropActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnRegister;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCourses;
    // End of variables declaration//GEN-END:variables
    /**
     * Populates the registration table with available courses and saved registration status.
     */
    private void populateCourseTable() {
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();

        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"Course", "CRN", "Credits", "Status"});

        addCourseRow(model, "INFO5100", "5100", "4");
        addCourseRow(model, "INFO6205", "6205", "4");
        addCourseRow(model, "INFO6105", "6105", "4");
        addCourseRow(model, "DAMG6210", "6210", "4");
    }

    /**
     * Adds one course row to the registration table using the student's saved status.
     *
     * @param model registration table model
     * @param courseCode course identifier
     * @param crn course registration number
     * @param credits course credit value
     */
    private void addCourseRow(DefaultTableModel model, String courseCode, String crn, String credits) {
        String status = student.isRegisteredForCourse(courseCode) ? "Registered" : "Available";
        model.addRow(new Object[]{courseCode, crn, credits, status});
    }

    /**
     * Registers the selected course for the current student.
     */
    private void registerCourse() {
        int selectedRow = tblCourses.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a course first.");
            return;
        }

        String status = tblCourses.getValueAt(selectedRow, 3).toString();

        if (status.equals("Registered")) {
            JOptionPane.showMessageDialog(this, "You are already registered for this course.");
            return;
        }

        String courseCode = tblCourses.getValueAt(selectedRow, 0).toString();
        student.registerCourse(courseCode);

        tblCourses.setValueAt("Registered", selectedRow, 3);
        JOptionPane.showMessageDialog(this, "Course registered successfully.");
    }

    /**
     * Drops the selected course for the current student.
     */
    private void dropCourse() {
        int selectedRow = tblCourses.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a course first.");
            return;
        }

        String status = tblCourses.getValueAt(selectedRow, 3).toString();

        if (!status.equals("Registered")) {
            JOptionPane.showMessageDialog(this, "You are not registered for this course.");
            return;
        }

        String courseCode = tblCourses.getValueAt(selectedRow, 0).toString();
        student.dropCourse(courseCode);

        tblCourses.setValueAt("Available", selectedRow, 3);
        JOptionPane.showMessageDialog(this, "Course dropped successfully.");
    }

    /**
     * Returns the user to the Student Work Area panel.
     */
    private void goBack() {
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }
}