/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;
import Business.Business;
import Business.Profiles.StudentAccount;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nicholaswoodward
 */
public class StudentGraduationAuditJPanel extends javax.swing.JPanel {
Business business;
StudentProfile student;
JPanel CardSequencePanel;
final StudentAccount studentAccount;
    /**
     * Creates new form StudentGraduationAuditJPanel
     */
    public StudentGraduationAuditJPanel(Business b, StudentAccount sa, StudentProfile sp, JPanel csp) {
    this.studentAccount = sa;
        business = b;
    student = sp;
    CardSequencePanel = csp;

    if (Business.Authorize(sa, "Student")) initComponents();

    populateGraduationAuditTable();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGraduationAudit = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnCheckEligibility = new javax.swing.JButton();

        lblTitle.setText("Graduation Audit");

        tblGraduationAudit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGraduationAudit);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCheckEligibility.setText("Check Eligibility");
        btnCheckEligibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckEligibilityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(btnCheckEligibility)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnCheckEligibility))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCheckEligibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckEligibilityActionPerformed
    checkEligibility();
    }//GEN-LAST:event_btnCheckEligibilityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckEligibility;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblGraduationAudit;
    // End of variables declaration//GEN-END:variables
private void populateGraduationAuditTable() {
    DefaultTableModel model = (DefaultTableModel) tblGraduationAudit.getModel();

    model.setRowCount(0);
    model.setColumnIdentifiers(new Object[]{"Requirement", "Completed", "Required", "Status"});

    int registeredCredits = student.getRegisteredCreditTotal();
    int completedCredits = 44 + registeredCredits;
    int requiredCredits = 52;
    int remainingCredits = requiredCredits - completedCredits;

    if (remainingCredits < 0) {
        remainingCredits = 0;
    }

    String status = completedCredits >= requiredCredits ? "Eligible" : "Not Eligible";

    model.addRow(new Object[]{"Completed Credits", completedCredits, requiredCredits, status});
    model.addRow(new Object[]{"Registered Current Credits", registeredCredits, "N/A", "In Progress"});
    model.addRow(new Object[]{"Remaining Credits", remainingCredits, "0", remainingCredits == 0 ? "Complete" : "Incomplete"});
    model.addRow(new Object[]{"Graduation Status", status, "Eligible", status});
}
private void checkEligibility() {
    int registeredCredits = student.getRegisteredCreditTotal();
    int completedCredits = 44 + registeredCredits;
    int requiredCredits = 52;
    int remainingCredits = requiredCredits - completedCredits;

    if (remainingCredits < 0) {
        remainingCredits = 0;
    }

    if (completedCredits >= requiredCredits) {
        JOptionPane.showMessageDialog(this,
                "Graduation Audit Summary\n\n"
                + "Status: ELIGIBLE\n"
                + "Completed Credits: " + completedCredits + "\n"
                + "Required Credits: " + requiredCredits,
                "Graduation Audit",
                JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this,
                "Graduation Audit Summary\n\n"
                + "Status: NOT ELIGIBLE\n"
                + "Completed Credits: " + completedCredits + "\n"
                + "Required Credits: " + requiredCredits + "\n"
                + "Remaining Credits: " + remainingCredits,
                "Graduation Audit",
                JOptionPane.INFORMATION_MESSAGE);
    }
}

private void goBack() {
    CardSequencePanel.remove(this);
    ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}}
