/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;


import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ManageUserAccountsJPanel extends javax.swing.JPanel {
    
    
    // ATTRIBUTES
    JPanel CardSequencePanel;
    Business business;
    UserAccount selecteduseraccount;

    
    // CONSTRUCTOR
    
    /**
     * Creates new form ManageUserAccountsJPanel
     * @param bz
     * @param jp
     */
    public ManageUserAccountsJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        refreshTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblUserAccounts = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccounts = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(30, 300, 74, 23);

        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        add(btnNext);
        btnNext.setBounds(500, 300, 80, 23);

        lblUserAccounts.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUserAccounts.setText("User Accounts");
        add(lblUserAccounts);
        lblUserAccounts.setBounds(30, 90, 190, 19);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Manage User Accounts");
        add(lblTitle);
        lblTitle.setBounds(21, 20, 550, 28);

        tblUserAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User Name", "Status", "Last Activity", "Last Updated"
            }
        ));
        tblUserAccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblUserAccountsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblUserAccounts);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 570, 130);

        btnDelete.setText("Delete Account");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(250, 300, 120, 23);

        btnAdd.setText("Add >>");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(500, 340, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to previous page
        
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // Load account update pane with selected user
        
        // Notify if user is not selected
        if(selecteduseraccount==null) {
            JOptionPane.showMessageDialog(null, "Please select an account from the table.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Load next page with user account if selected
        UpdateUserAccount mppd = new UpdateUserAccount(selecteduseraccount, CardSequencePanel);
        CardSequencePanel.add(mppd);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnNextActionPerformed

    private void tblUserAccountsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserAccountsMousePressed
        // Extracts the selected user account from the table

        int selectedrow = tblUserAccounts.getSelectedRow();

        if (selectedrow < 0 || selectedrow > tblUserAccounts.getRowCount()) {
            return;
        }
        
        selecteduseraccount = (UserAccount) tblUserAccounts.getValueAt(selectedrow, 0);            
    }//GEN-LAST:event_tblUserAccountsMousePressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Remove selected account from user directory + update table
        
        // Notify if no user is selected / if user is currently logged in
        if (selecteduseraccount == null) {
            JOptionPane.showMessageDialog(null, "Please select an account from the table.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (selecteduseraccount.getStatus()) {
            JOptionPane.showMessageDialog(null, "Cannot delete account as user is currently logged in.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Display confirmation dialog for deletion
        int dialogResult = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete the selected account?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            UserAccountDirectory uad = business.getUserAccountDirectory();
            uad.deleteUserAccount(selecteduseraccount);
            selecteduseraccount = null;
            refreshTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Load user account creation page
        CreateUserAccount cua = new CreateUserAccount(business, CardSequencePanel);
        CardSequencePanel.add(cua);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserAccounts;
    private javax.swing.JTable tblUserAccounts;
    // End of variables declaration//GEN-END:variables

    
    // EXTRA METHODS
    public void refreshTable() {
        // Update table with current values from UserDirectory
        
        // Clear table
        DefaultTableModel model =  (DefaultTableModel) tblUserAccounts.getModel();
        model.setRowCount(0);
        
        // Add each entry to table
        UserAccountDirectory uad = business.getUserAccountDirectory();
        for (UserAccount ua : uad.getUserAccountList()) {
            Object[] row = new Object[5];
            row[0] = ua;
            row[1] = (ua.getStatus()) ? "Logged In" : "Disconnected";
            row[2] = ua.getActivity();
            row[3] = ua.getUpdated();
            
            model.addRow(row);
        }
    }
}