/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Profiles.StudentAccount;
import Business.UserAccounts.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *h
 * @author kal bugrara
 */

public class UpdateUserAccount extends javax.swing.JPanel {
    
    
    // ATTRIBUTES
    JPanel CardSequencePanel;
    UserAccount selecteduseraccount;

    
    // CONSTRUCTOR
    
    /**
     * Creates new form AdminUserAccount
     * @param sua
     * @param jp
     */
    public UpdateUserAccount(UserAccount sua, JPanel jp) {
        CardSequencePanel = jp;
        selecteduseraccount= sua;
        initComponents();
        //display user details here
        updateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblActivity = new javax.swing.JLabel();
        txtActivity = new javax.swing.JTextField();
        txtUpdated = new javax.swing.JTextField();
        lblUpdated = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblProfile = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtProfileType = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        lblNUID = new javax.swing.JLabel();
        txtNUID = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnUpdate.setText("Update >>");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(480, 380, 100, 23);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Update User Account");
        add(lblTitle);
        lblTitle.setBounds(21, 20, 550, 28);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 380, 100, 23);

        lblActivity.setText("Last Activity:");
        add(lblActivity);
        lblActivity.setBounds(180, 120, 80, 20);

        txtActivity.setEditable(false);
        add(txtActivity);
        txtActivity.setBounds(270, 120, 190, 22);

        txtUpdated.setEditable(false);
        add(txtUpdated);
        txtUpdated.setBounds(270, 160, 190, 22);

        lblUpdated.setText("Last Updated:");
        add(lblUpdated);
        lblUpdated.setBounds(180, 160, 80, 20);

        lblUsername.setText("Username:");
        add(lblUsername);
        lblUsername.setBounds(350, 230, 80, 20);
        add(txtUsername);
        txtUsername.setBounds(450, 230, 110, 22);
        add(txtPassword);
        txtPassword.setBounds(450, 260, 110, 22);

        lblPassword.setText("Password:");
        add(lblPassword);
        lblPassword.setBounds(350, 260, 80, 20);

        lblProfile.setText("Profile Type:");
        add(lblProfile);
        lblProfile.setBounds(60, 260, 80, 20);

        lblID.setText("Profile ID:");
        add(lblID);
        lblID.setBounds(60, 230, 70, 20);

        txtProfileType.setEditable(false);
        add(txtProfileType);
        txtProfileType.setBounds(140, 260, 110, 22);

        txtID.setEditable(false);
        add(txtID);
        txtID.setBounds(140, 230, 110, 22);

        lblNUID.setText("NUID:");
        add(lblNUID);
        lblNUID.setBounds(60, 290, 60, 20);

        txtNUID.setEditable(false);
        add(txtNUID);
        txtNUID.setBounds(140, 290, 110, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // Update fields and notify user, then return to user account table page

        String username = txtUsername.getText();
        String password = txtPassword.getText();
        
        // Null/Blank check
        if (username == null || password == null || username.isBlank() || password.isBlank()) {
            JOptionPane.showMessageDialog(null, "Username/Password cannot be blank.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Update and display confirmation
        selecteduseraccount.setUserLoginName(username);
        selecteduseraccount.setPassword(password);
        selecteduseraccount.setUpdated();
        JOptionPane.showMessageDialog(null, "User account successfully updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        // Update table on previous page and return
        CardSequencePanel.remove(this);
        
        Component[] panelStack = CardSequencePanel.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];
        ManageUserAccountsJPanel manageUserAccountsJPanel = (ManageUserAccountsJPanel) lastPanel;
        manageUserAccountsJPanel.refreshTable(); // Update table
        manageUserAccountsJPanel.selecteduseraccount = null; // Deselect account
        
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to previous page
        
        CardSequencePanel.remove(this);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblActivity;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNUID;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUpdated;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtActivity;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNUID;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtProfileType;
    private javax.swing.JTextField txtUpdated;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    
    // EXTRA METHODS
    private void updateFields() {
        // Load updated data into fields
        
        String role = selecteduseraccount.getRole();
        
        txtActivity.setText(selecteduseraccount.getActivity());
        txtUpdated.setText(selecteduseraccount.getUpdated());
        txtProfileType.setText(role);
        txtID.setText(selecteduseraccount.getPersonId());
        txtUsername.setText(selecteduseraccount.getUserLoginName());
        txtPassword.setText(selecteduseraccount.getPassword());
        
        if (selecteduseraccount instanceof StudentAccount) {
            lblNUID.setVisible(true);
            txtNUID.setVisible(true);
            
            txtNUID.setText(String.valueOf(((StudentAccount)selecteduseraccount).getNUID()));
        } else {
            lblNUID.setVisible(false);
            txtNUID.setVisible(false);
        }
    }
}