/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.ManageStudents;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.StudentDirectory;
import Business.Profiles.StudentProfile;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.AdministerPersonJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abala
 */
public class ManageStudentsJPanel extends javax.swing.JPanel {

    
    // ATTRIBUTES
    Business business;
    JPanel CardSequencePanel;
    
    
    // CONSTRUCTOR
    
    /**
     * Creates new form ManageStudentsJPanel
     * @param bz
     * @param csp
     */
    public ManageStudentsJPanel(Business bz, JPanel csp) {
        this.business = bz;
        CardSequencePanel = csp;
        initComponents();
        
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Manage Students");

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(416, 416, 416)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(btnNext))
                .addGap(32, 32, 32)
                .addComponent(btnDelete)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to previous page
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // Ensure person is selected then load person management pane

        int selectedRow = tblStudents.getSelectedRow();
        if (selectedRow < 0 || selectedRow > tblStudents.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Please select a student from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Find the corresponding student profile and corresponding null check
        StudentDirectory sd = business.getStudentDirectory();
        StudentProfile selectedStudent =  sd.findStudent((String) tblStudents.getValueAt(selectedRow, 0));
        if (selectedStudent == null) {
            JOptionPane.showMessageDialog(null, "Profile could not be found for selected student.",  "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        UpdateStudentJPanel usp = new UpdateStudentJPanel(business, selectedStudent, CardSequencePanel);
        CardSequencePanel.add(usp);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Remove selected account from student directory + update table
        
        // Notify if no user is selected
        int selectedRow = tblStudents.getSelectedRow();
        if (selectedRow < 0 || selectedRow > tblStudents.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Find the corresponding student profile and corresponding null check
        StudentDirectory sd = business.getStudentDirectory();
        StudentProfile selectedStudent =  sd.findStudent((String) tblStudents.getValueAt(selectedRow, 0));
        if (selectedStudent == null) {
            JOptionPane.showMessageDialog(null, "Profile could not be found for selected student.",  "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Display confirmation dialog for deletion
        int dialogResult = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete the selected student profile?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            sd.deleteStudentProfile(selectedStudent);
            refreshTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblStudents;
    // End of variables declaration//GEN-END:variables

    
    // EXTRA METHODS
    public void refreshTable() {
        // Update table with current values from StudentDirectory
        
        // Clear table
        DefaultTableModel model =  (DefaultTableModel) tblStudents.getModel();
        model.setRowCount(0);
        
        // Add each entry to table
        StudentDirectory sd = business.getStudentDirectory();
        for (StudentProfile sp : sd.getList()) {
            Object[] row = new Object[1];
            row[0] = sp.getPerson().getPersonId();
            
            model.addRow(row);
        }
    }
}
