/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.ManageStudents;

import Business.Business;
import Business.Profiles.StudentAccount;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp.ManageUserAccountsJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author abala
 */
public class UpdateStudentJPanel extends javax.swing.JPanel {

    
    // ATTRIBUTES
    Business business;
    StudentProfile student;
    JPanel CardSequencePanel;
    StudentAccount studentUser;
    
    /**
     * Creates new form UpdateStudentJPanel
     * @param bz
     * @param sp
     * @param csp
     */
    public UpdateStudentJPanel(Business bz, StudentProfile sp, JPanel csp) {
        this.business = bz;
        this.student = sp;
        CardSequencePanel = csp;
        initComponents();
        
        updateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblNUID = new javax.swing.JLabel();
        txtNUID = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));

        btnUpdate.setText("Update >>");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Update User Account");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblID.setText("Name:");

        lblNUID.setText("NUID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(340, 340, 340)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(txtNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle)
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(btnUpdate))
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // Update fields and notify user, then return to student management page

        String name = txtName.getText();
        Integer id = null;

        // Blank checks
        if (name.isBlank()) {
            JOptionPane.showMessageDialog(null, "Name cannot be blank.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        // NUID check if student already has account
        if (studentUser != null) {
            try {
                id = Integer.valueOf(txtNUID.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "NUID must be an integer.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        // Update valid fields and display confirmation
        student.getPerson().setPersonId(name);
        if (studentUser != null) {
            studentUser.setNUID(id);
        }
        
        JOptionPane.showMessageDialog(null, "User account successfully updated!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Update table on previous page and return
        CardSequencePanel.remove(this);

        Component[] panelStack = CardSequencePanel.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];
        ManageStudentsJPanel manageStudentsJPanel = (ManageStudentsJPanel) lastPanel;
        manageStudentsJPanel.refreshTable(); // Update table

        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to previous page

        CardSequencePanel.remove(this);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNUID;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtNUID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    
    // EXTRA METHODS
    private void updateFields() {
        // Load name and NUID if student has an account
        
        // Display name
        String name = student.getPerson().getPersonId();
        txtName.setText(name);
        
        // Display NUID if applicable
        UserAccount ua = business.getUserAccountDirectory().findUserAccount(name);
        if (ua instanceof StudentAccount) {
            txtNUID.setVisible(true);
            lblNUID.setVisible(true);
            
            studentUser = (StudentAccount) ua;
            
            txtNUID.setText(String.valueOf(studentUser.getNUID()));
        } else {
            txtNUID.setVisible(false);
            lblNUID.setVisible(false);
            
            studentUser = null;
        }
    }
}
